#!/bin/sh

set -efux

vmm_dir="$HOME/vmm"
images_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/images"

replace=1
vm_name="$1"

vm_dir="$vmm_dir/$vm_name"
monitor_socket_path="$vm_dir/monitor.socket"

if [ -d "$vm_dir" ]; then
	[ "$replace" -eq 1 ] || exit 1

	[ ! -S "$monitor_socket_path" ] || {
		printf "quit\n" | socat - "unix:$monitor_socket_path"
	}

	rm -rf "$vm_dir"
fi

vm_mac_address="52:54:00:$(printf '%s' "$vm_name" | gzip -1 -c | tail -c8 | od -t x4 -N 4 -A n | tail -c7 | sed -E 's/([a-f0-9]{2})/\1:/g' | head -c8)"

mkdir -p "$vm_dir"

vm_disk_path="$vm_dir/disk.qcow2"
vm_cloud_init_drive_path="$vm_dir/cloud_init_drive.img"

mkdir -p "$images_dir"

image_path="$images_dir/alt-sisyphus"
image_url='https://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/x86_64/alt-sisyphus-cloud-x86_64.qcow2'

if [ ! -f "$image_path" ]; then
	curl "$image_url" -O "$image_path"
fi

qemu-img create -b "$image_path" -F qcow2 -f qcow2 "$vm_disk_path" 10G

ssh_key_path="$vm_dir/id_ed25519"

ssh-keygen -t ed25519 -f "$ssh_key_path" -N ''

pub_ssh_key_path="${ssh_key_path}.pub"
pub_ssh_key="$(cat "$pub_ssh_key_path")"

user_data_path="$vm_dir/user-data.yaml"

cat <<EOF > "$user_data_path"
#cloud-config
disable_root: false
users:
  - name: root
    lock_passwd: false
    plain_text_passwd: "123"
    ssh_authorized_keys:
      - ${pub_ssh_key}
preserve_hostname: false
hostname: ${vm_name}
EOF

networking='user'

if [ "$networking" = 'user' ]; then
	cloud-localds "$vm_cloud_init_drive_path" "$user_data_path"
fi

set -- -accel kvm \
	-cpu host \
	-m 2048 \
	-smp 2 \
	-display none \
	-daemonize \
	-monitor "unix:${monitor_socket_path},server=on,wait=off" \
	-blockdev "driver=qcow2,node-name=disk1,file.driver=file,file.filename=${vm_disk_path},discard=unmap" \
	-device virtio-blk-pci,drive=disk1 \
	-blockdev "driver=raw,node-name=cloud-init-drive,file.driver=file,file.filename=${vm_cloud_init_drive_path},read-only=on,force-share=on" \
	-device virtio-blk-pci,drive=cloud-init-drive

vm_config_path="$vm_dir/vmm.conf"

if [ "$networking" = 'user' ]; then
	port=24000
	while [ "$(ss --no-header --tcp state all sport "$port" | wc -l)" -ne 0 ]; do
		port=$((port + 1))
	done

	echo "ssh_port=$port" > "$vm_config_path"

	set -- "$@" -netdev "user,id=net0,hostfwd=tcp:127.0.0.1:${port}-:22" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address}"
fi

qemu-system-x86_64 "$@"
