#!/usr/bin/env sh

PROG="${0##*/}"

. svmm-common

show_help()
{
	cat <<-EOF
	svmm-rm [options] [VM_NAME]

	Options:
	  -a, --all			remove all VMs
	  -f, --force			remove VM even if it is currently running
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

error()
{
	printf '%s: %s\n' "$PROG" "$1" >&2
}

vm_name=
all=0
force=0
verbose=0
while true; do
	case "$1" in
	-v | --verbose)
		verbose=1
		shift
		;;
	-h | --help)
		show_help
		exit 0
		;;
	-a | --all)
		all=1
		shift
		;;
	-f | --force)
		force=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

if [ "$all" -eq 1 ]; then
	for vm_dir in "$vmm_dir"/*; do
		[ -d "$vm_dir" ] || continue

		vm_name="${vm_dir##*/}"
		qmp_socket_path="$vm_dir/qmp.socket"

		if svmm-is-qemu-running "$vm_name"; then
			if [ "$force" -ne 1 ]; then
				error "Cannot remove VM '$vm_name' - as it is running"
				continue
			fi
			qmp "$qmp_socket_path" '{"execute": "quit"}' > /dev/null
			wait_qemu_exit "$vm_dir"
		fi

		rm -rf "$vm_dir"
	done
	exit
fi

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

vm_dir="$vmm_dir/$vm_name"
qmp_socket_path="$vm_dir/qmp.socket"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"

if svmm-is-qemu-running "$vm_name"; then
	[ "$force" -eq 1 ] || fatal "$vm_name is running"
	qmp "$qmp_socket_path" '{"execute": "quit"}' > /dev/null
	wait_qemu_exit "$vm_dir"
fi

rm -rf "$vm_dir"
