#!/usr/bin/env sh

set -efux

PROG=svmm-dnsmasq
. svmm-common

dnsmasq --log-queries --interface=svmmdynamicbr0 --listen-address=172.16.2.1 --bind-interface --no-daemon --dhcp-range=172.16.2.2,172.16.2.100 --dhcp-option=option:ntp-server,172.16.2.1 --dhcp-leasefile="$dnsmasq_leases_file"
