#!/usr/bin/env sh

set -f

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

show_help()
{
	cat <<-EOF
	svmm-snapshot [options] VM_NAME SNAPSHOT_NAME

	Options:
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

vm_name=
snapshot_name=
verbose=0
while true; do
	case "$1" in
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		[ -n "$1" ] || break

		if [ -z "$vm_name" ]; then
			vm_name="$1"
		else
			snapshot_name="$1"
		fi
		shift
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'
[ -n "$snapshot_name" ] || fatal 'SNAPSHOT_NAME is not specified'

vm_dir="$vmm_dir/$vm_name"
vm_config_path="$vm_dir/vmm.conf"
monitor_socket_path="$vm_dir/monitor.socket"

[ ! -S "$monitor_socket_path" ] || fatal "making live snapshots is not supported, first stop VM '$vm_name'"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"

. "$vm_config_path"

# defaults for VMs created before these were saved in the config
: "${vm_disk_path:=$vm_dir/disk}"
: "${boot_drive_format:=qcow2}"

[ "$boot_drive_format" = 'qcow2' ] || fatal "internal snapshots are only supported on qcow2 drives, VM '$vm_name' uses '$boot_drive_format'"

qemu-img snapshot -c "$snapshot_name" "$vm_disk_path"

if [ -n "${second_drive}" ]; then
	qemu-img snapshot -c "$snapshot_name" "$second_drive"
fi
