#!/usr/bin/env sh

set -f

PROG="${0##*/}"

ovmf_dir='/usr/share/OVMF'

vmm_dir="$HOME/vmm"
images_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/images"
iso_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/iso"

default_boot_drive_url='https://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/x86_64/alt-sisyphus-cloud-x86_64.qcow2'
# TODO: use qemu-img info to autodetect the format
default_boot_drive_format='qcow2'
default_disk_size='10G'
default_memory='2G'
default_cores='2'

show_help()
{
	cat <<-EOF
	svmm-run [options] VM_NAME

	Options:
	  --memory <MEM>				sets guest RAM size to MEM (default: $default_memory)
	  --cores <NUM>					sets the number of CPUs to NUM (default: $default_cores)
	  --kvm						enable hardware accelaration using KVM
	  --cpu <CPU>					emulate selected CPU
	  --replace					first delete VM with this name if it already exists
	  --iso-path <path>				attach the ISO at this path to the VM as cdrom
	  --iso-url <URL>				attach the ISO at this url to the VM as cdrom
	  --create-boot-drive				create empty qcow2 file as boot drive for the VM
	  --disk-size <GB>				allocate this much disk space for the boot drive (default: $default_disk_size)
	  --boot-drive-url <URL>			use file at this url as boot image (default: $default_boot_drive_url)
	  --boot-drive-format <FORMAT>			file format of boot image (default: $default_boot_drive_format)
	  --second-drive <path>				path to qcow2 file to attach another drive to the VM
	  --net-tap <tap>				use QEMU tap networking and connect VM's NIC to tap device with this name
	  --net-address-cidr <IP-CIDR>			assign this IP address and network mask to the VM's network interface
	  --net-gateway <IP>				use this IP as the default gateway in the VM
	  --net-dhcp					enable dhcp discovery in VM
	  --cloud-init-network-config-version <VERSION>	use specified network-config version (1 or 2, default: 2)
	  --spice					enable and connect to SPICE
	  --gtk						use gtk GUI for VM output
	  --vnc <number>				enable and start vnc server on port 5900+<number>
	  --no-cloud-init-drive				don't attach cloud-init drive for NoCloud datasource
	  --log-serial					redirect serial port to a file
	  --uefi					use UEFI (OVMF) instead of legacy BIOS (SeaBIOS)
	  --uefi-empty-varstore				use empty OVMF_VARS file (no secure boot keys enrolled)
	  --guest-agent					enable qemu guest agent support for this VM
	  --kernel <PATH>				boot the kernel at PATH directly
	  --initramfs <PATH>				use initramfs at PATH when direct kernel booting
	  --append-cmdline <CMDLINE>			use CMDLINE as the kernel command line
	  --gdb						enable gdb server
	  --dry-run					print qemu command, which would be run, but don't actually run qemu
	  -v, --verbose					print executed commands
	  -h, --help					show help and exit
	EOF
}

fatal()
{
	printf '%s: %s\n' "$PROG" "$1" >&2
	exit 1
}

fetch()
{
	url=$1
	dest=$2
	tmp="$dest.partial"
	curl "$url" --output "$tmp" --fail --location || { rm -f "$tmp"; fatal "Failed to download '$url'"; }
	mv "$tmp" "$dest"
}

vm_name=
verbose=0
memory=
cores=
enable_kvm=0
cpu=
replace=0
iso_path_option=
iso_url=
create_boot_drive=0
disk_size=
boot_drive_url=
boot_drive_format=
second_drive=
network_tap_device_name=
network_vm_ip_address_cidr=
network_vm_default_gateway=
network_vm_dhcp=0
cloud_init_network_config_version=2
enable_spice=0
display_gtk=0
vnc=
attach_cloud_init_drive=1
log_serial=0
uefi=0
uefi_empty_varstore=0
enable_tpm=0
enable_qemu_guest_agent=0
kernel_path=
initramfs_path=
append_cmdline=
enable_gdb=0
cloud_init_user_data_path=
dry_run=0
while true; do
	case "$1" in
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	--memory)
		memory="$2"
		shift 2
		;;
	--cores)
		cores="$2"
		shift 2
		;;
	--kvm)
		enable_kvm=1
		shift
		;;
	--cpu)
		cpu="$2"
		shift 2
		;;
	--replace)
		replace=1
		shift
		;;
	--iso-path)
		iso_path_option="$2"
		shift 2
		;;
	--iso-url)
		iso_url="$2"
		shift 2
		;;
	--create-boot-drive)
		create_boot_drive=1
		shift
		;;
	--disk-size)
		disk_size="$2"
		shift 2
		;;
	--boot-drive-url)
		boot_drive_url="$2"
		shift 2
		;;
	--boot-drive-format)
		boot_drive_format="$2"
		shift 2
		;;
	--second-drive)
		second_drive="$2"
		shift 2
		;;
	--net-tap)
		network_tap_device_name="$2"
		shift 2
		;;
	--net-address-cidr)
		network_vm_ip_address_cidr="$2"
		shift 2
		;;
	--net-gateway)
		network_vm_default_gateway="$2"
		shift 2
		;;
	--net-dhcp)
		network_vm_dhcp=1
		shift 1
		;;
	--cloud-init-network-config-version)
		cloud_init_network_config_version="$2"
		shift 2
		;;
	--spice)
		enable_spice=1
		shift
		;;
	--gtk)
		display_gtk=1
		shift
		;;
       --vnc)
               vnc="$2"
               shift 2
               ;;
	--no-cloud-init-drive)
		attach_cloud_init_drive=0
		shift
		;;
	--log-serial)
		log_serial=1
		shift
		;;
	--uefi)
		uefi=1
		shift
		;;
	--uefi-empty-varstore)
		uefi_empty_varstore=1
		shift
		;;
	--tpm)
		enable_tpm=1
		shift
		;;
	--guest-agent)
		enable_qemu_guest_agent=1
		shift
		;;
	--kernel)
		kernel_path="$2"
		shift 2
		;;
	--initramfs)
		initramfs_path="$2"
		shift 2
		;;
	--append-cmdline)
		append_cmdline="$2"
		shift 2
		;;
	--gdb)
		enable_gdb=1
		shift
		;;
	--cloud-init-user-data)
		cloud_init_user_data_path="$2"
		shift 2
		;;
	--dry-run)
		dry_run=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'
[ -n "$boot_drive_url" ] || boot_drive_url="$default_boot_drive_url"
[ -n "$boot_drive_format" ] || boot_drive_format="$default_boot_drive_format"
[ -n "$memory" ] || memory="$default_memory"
[ -n "$cores" ] || cores="$default_cores"
[ -n "$disk_size" ] || disk_size="$default_disk_size"

vm_dir="$vmm_dir/$vm_name"
vm_config_path="$vm_dir/vmm.conf"
monitor_socket_path="$vm_dir/monitor.socket"
qemu_pid_file_path="$vm_dir/qemu_pid"

if [ -d "$vm_dir" ]; then
	[ "$replace" -eq 1 ] || fatal "VM '$vm_name' already exists"

	if [ -S "$monitor_socket_path" ]; then
		{ echo '{"execute":"qmp_capabilities"}' && echo '{"execute": "quit"}'; } | socat STDIO "UNIX-CONNECT:$monitor_socket_path" > /dev/null
	fi

	rm -rf "$vm_dir"
fi

vm_mac_address="52:54:00:$(printf '%s' "$vm_name" | crc32 /dev/stdin | tail -c7 | sed -E 's/([a-f0-9]{2})/\1:/g' | head -c8)"

mkdir -p "$vm_dir"

vm_disk_path="$vm_dir/disk"
vm_cloud_init_dir="$vm_dir/cloud-init"
vm_cloud_init_drive_path="$vm_cloud_init_dir/cloud_init_drive.img"

mkdir -p "$images_dir"
mkdir -p "$iso_dir"

boot_drive_path="$images_dir/${boot_drive_url##*/}"
{ [ -n "$iso_path_option" ] && iso_path=$iso_path_option; } || { [ -n "$iso_url" ] && iso_path=$iso_dir/${iso_url##*/}; }

if [ "$create_boot_drive" -eq 0 ] && [ ! -f "$boot_drive_path" ]; then
	echo "Downloading boot drive image from '$boot_drive_url'" >&2
	fetch "$boot_drive_url" "$boot_drive_path"
fi

if [ -n "$iso_url" ] && [ ! -f "$iso_path" ]; then
	echo "Downloading ISO from '$iso_url'" >&2
	fetch "$iso_url" "$iso_path"
fi

if [ "$create_boot_drive" -eq 0 ]; then
	if [ "$boot_drive_format" = 'qcow2' ]; then
		qemu-img create -b "$boot_drive_path" -B "$boot_drive_format" -f "$boot_drive_format" "$vm_disk_path" "$disk_size" > /dev/null || fatal "Failed to create a boot drive for '$vm_name' from '$boot_drive_url'"
	elif [ "$boot_drive_format" = 'raw' ]; then
		cp -a "$boot_drive_path" "$vm_disk_path" > /dev/null || fatal "Failed to copy the boot drive image for '$vm_name' from '$boot_drive_path'"
		if [ "${boot_drive_url##*.}" = 'xz' ]; then
			mv "$vm_disk_path" "$vm_disk_path.xz"
			xz -d "$vm_disk_path.xz" || fatal "Failed to decompress boot drive '$vm_disk_path' (from '$boot_drive_path')"
		fi
		mv "$vm_disk_path" "$vm_disk_path.$boot_drive_format"
		vm_disk_path=$vm_disk_path.$boot_drive_format
		qemu-img resize "$vm_disk_path" "$disk_size"
	else
		fatal "Unknown boot drive file format '$boot_drive_format'"
	fi
else
	qemu-img create -f qcow2 "$vm_disk_path" "$disk_size" > /dev/null || fatal "Failed to create a new empty boot drive for '$vm_name'"
	boot_drive_format=qcow2
fi

echo "vm_disk_path=$vm_disk_path" >> "$vm_config_path"
echo "memory=$memory" >> "$vm_config_path"
echo "cores=$cores" >> "$vm_config_path"

[ -n "$network_tap_device_name" ] && network_type='tap' || network_type='user'

echo "network_type=$network_type" >> "$vm_config_path"

if [ "$attach_cloud_init_drive" -eq 1 ]; then
	mkdir -p "$vm_cloud_init_dir"

	ssh_key_path="$vm_dir/id_ed25519"

	ssh-keygen -t ed25519 -f "$ssh_key_path" -N '' > /dev/null

	pub_ssh_key_path="${ssh_key_path}.pub"
	pub_ssh_key="$(cat "$pub_ssh_key_path")"

	user_data_path="$vm_cloud_init_dir/user-data"

	if [ -n "$cloud_init_user_data_path" ]; then
		cp -a "$cloud_init_user_data_path" "$user_data_path" || fatal "Failed to copy user-data from '$cloud_init_user_data_path'"
	else
		cat <<-EOF > "$user_data_path"
		#cloud-config
		disable_root: false
		users:
		  - name: root
		    lock_passwd: false
		    plain_text_passwd: "123"
		    ssh_authorized_keys:
		      - ${pub_ssh_key}
		hostname: ${vm_name}
		EOF
	fi

	if [ "$network_type" = 'user' ]; then
		cloud-localds --hostname "$vm_name" "$vm_cloud_init_drive_path" "$user_data_path"
	else
		network_config_path="$vm_cloud_init_dir/network-config"

		if [ "$network_vm_dhcp" -eq 1 ]; then
			if [ "$cloud_init_network_config_version" = '1' ]; then
				fatal 'not implemented'
			elif [ "$cloud_init_network_config_version" = '2' ]; then
				cat <<-EOF > "$network_config_path"
				version: 2
				ethernets:
				  interface0:
				    match:
				      name: "e*"
				    dhcp4: true
				EOF
			else
				fatal "unknown cloud-init network-config version: '$cloud_init_network_config_version'"
			fi
		else
			[ -n "${network_vm_ip_address_cidr}" ] || fatal '--net-address-cidr is not set'
			[ -n "${network_vm_default_gateway}" ] || fatal '--net-gateway is not set'

			if [ "$cloud_init_network_config_version" = '1' ]; then
				cat <<-EOF > "$network_config_path"
				version: 1
				config:
				  - type: physical
				    name: eth0
				    mac_address: "$vm_mac_address"
				    subnets:
				      - type: static
				        address: $network_vm_ip_address_cidr
				        gateway: $network_vm_default_gateway
				        dns_nameservers:
				          - 8.8.8.8
				EOF
			elif [ "$cloud_init_network_config_version" = '2' ]; then
				cat <<-EOF > "$network_config_path"
				version: 2
				ethernets:
				  interface0:
				    match:
				      name: "e*"
				    addresses:
				      - ${network_vm_ip_address_cidr:?}
				    routes:
				      - to: 0.0.0.0/0
				        via: ${network_vm_default_gateway:?}
				    nameservers:
				      addresses:
				        - 8.8.8.8
				EOF
			else
				fatal "unknown cloud-init network-config version: '$cloud_init_network_config_version'"
			fi
		fi

		cloud-localds --hostname "$vm_name" --network-config "$network_config_path" "$vm_cloud_init_drive_path" "$user_data_path"
	fi
fi

vm_uuid="$(uuidgen)"
echo "vm_uuid=$vm_uuid" >> "$vm_config_path"

echo "boot_drive_format=$boot_drive_format" >> "$vm_config_path"

set -- -name "$vm_name" \
	-m "$memory" \
	-smp "$cores" \
	-daemonize \
	-nodefaults \
	-pidfile "$qemu_pid_file_path" \
	-smbios "type=1,uuid=$vm_uuid" \
	-chardev "socket,id=qmp,path=${monitor_socket_path},server=on,wait=off" \
	-mon chardev=qmp,mode=control,pretty=off \
	-blockdev "node-name=disk1,discard=unmap,driver=${boot_drive_format},file.driver=file,file.filename=${vm_disk_path}" \
	-device virtio-blk-pci,drive=disk1,bootindex=0

echo "kvm=$enable_kvm" >> "$vm_config_path"

if [ "$enable_kvm" -eq 1 ]; then
	set -- "$@" -accel kvm
fi

if [ -n "$cpu" ]; then
	echo "cpu=$cpu" >> "$vm_config_path"
	set -- "$@" -cpu "$cpu"
else
	echo "cpu=''" >> "$vm_config_path"
fi

if [ -n "$vnc" ]; then
	case "$vnc" in
		*:*) ;;
		*) vnc=":$vnc" ;;
	esac
	echo "vnc=$vnc" >> "$vm_config_path"
	set -- "$@" -vnc "$vnc"
fi

if [ "$attach_cloud_init_drive" -eq 1 ]; then
	set -- "$@" -blockdev "node-name=cloud-init-drive,read-only=on,force-share=on,driver=raw,file.driver=file,file.filename=${vm_cloud_init_drive_path}" \
		-device virtio-blk-pci,drive=cloud-init-drive
fi

echo "attach_cloud_init_drive=$attach_cloud_init_drive" >> "$vm_config_path"

if [ -n "$second_drive" ]; then
	echo "second_drive=$second_drive" >> "$vm_config_path"

	set -- "$@" -blockdev "node-name=disk2,discard=unmap,driver=qcow2,file.driver=file,file.filename=${second_drive}" \
		-device virtio-blk-pci,drive=disk2
fi

if [ -n "$iso_path_option" ] || [ -n "$iso_url" ]; then
	set -- "$@" -blockdev "node-name=cdrom1-drive,read-only=on,force-share=on,driver=raw,file.driver=file,file.filename=$iso_path" \
		-device ide-cd,id=cdrom1,drive=cdrom1-drive,bootindex=1
fi

if [ "$network_type" = 'user' ]; then
	port=24000
	while [ "$(ss --no-header --tcp state all sport "$port" | wc -l)" -ne 0 ]; do
		port=$((port + 1))
	done

	echo "ssh_port=$port" >> "$vm_config_path"

	set -- "$@" -netdev "user,id=net0,hostfwd=tcp:127.0.0.1:${port}-:22" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address}"
fi

if [ "$network_type" = 'tap' ]; then
	echo "network_tap_device_name=$network_tap_device_name" >> "$vm_config_path"

	set -- "$@" -netdev "tap,id=net0,ifname=${network_tap_device_name},script=no" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address}"
fi

echo "vm_mac_address=$vm_mac_address" >> "$vm_config_path"
echo "enable_spice=$enable_spice" >> "$vm_config_path"

if [ "$enable_spice" -eq 1 ]; then
	set -- "$@" -display spice-app
elif [ "$display_gtk" -eq 1 ]; then
	set -- "$@" -display gtk -device VGA
else
	set -- "$@" -display none
fi

echo "log_serial=$log_serial" >> "$vm_config_path"

if [ "$log_serial" -eq 1 ]; then
	qemu_serial_log_path="$vm_dir/serial-$(date +%Y%m%d-%H%M%S).log"
	set -- "$@" -serial "file:$qemu_serial_log_path"
fi

echo "uefi=$uefi" >> "$vm_config_path"

if [ "$uefi" -eq 1 ]; then
	if [ "$uefi_empty_varstore" -eq 1 ]; then
		cp -a "$ovmf_dir/OVMF_VARS_4M.qcow2" "$vm_dir/OVMF_VARS_4M.qcow2"
	else
		cp -a "$ovmf_dir/OVMF_VARS_4M.secboot.qcow2" "$vm_dir/OVMF_VARS_4M.qcow2"
	fi

	set -- "$@" -machine q35 \
		-drive "if=pflash,format=qcow2,readonly=on,file=$ovmf_dir/OVMF_CODE_4M.secboot.qcow2" \
		-drive "if=pflash,format=qcow2,file=$vm_dir/OVMF_VARS_4M.qcow2"
fi

echo "enable_tpm=$enable_tpm" >> "$vm_config_path"

if [ "$enable_tpm" -eq 1 ]; then
	mkdir -p "$XDG_RUNTIME_DIR/swtpm"
	mkdir -p "$vm_dir/tpm2"
	swtpm socket \
		--ctrl "type=unixio,path=$XDG_RUNTIME_DIR/swtpm/$vm_name-swtpm.sock,mode=0600" \
		--tpmstate "dir=$vm_dir/tpm2,mode=0600,lock" \
		--log "file=$vm_dir/$vm_name-swtpm.log" \
		--terminate \
		--tpm2 &

	set -- "$@" -chardev "socket,id=chrtpm,path=$XDG_RUNTIME_DIR/swtpm/$vm_name-swtpm.sock" \
		-tpmdev emulator,id=tpm0,chardev=chrtpm \
		-device tpm-crb,tpmdev=tpm0
fi

echo "enable_qemu_guest_agent=$enable_qemu_guest_agent" >> "$vm_config_path"

if [ "$enable_qemu_guest_agent" -eq 1 ]; then
	set -- "$@" -chardev "socket,path=$vm_dir/qemu_guest_agent.sock,server=on,wait=off,id=qga0" \
		-device virtio-serial \
		-device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0
fi

if [ -n "$kernel_path" ]; then
	set -- "$@" -kernel "${kernel_path:?}" -initrd "${initramfs_path:?}"
	if [ -n "$append_cmdline" ]; then
		set -- "$@" -append "${append_cmdline:?}"
	fi
fi

if [ "$enable_gdb" -eq 1 ]; then
	set -- "$@" -s -S
fi

if [ "$dry_run" -eq 1 ]; then
	echo qemu-system-x86_64 "$@"
else
	qemu-system-x86_64 "$@"
fi
