#!/usr/bin/env sh

set -f

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

ovmf_dir='/usr/share/OVMF'

images_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/images"
iso_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/iso"

default_boot_drive_url='https://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/x86_64/alt-sisyphus-cloud-x86_64.qcow2'
default_disk_size='10G'
default_memory='2G'
default_cores='2'

show_help()
{
	cat <<-EOF
	svmm-run [options] VM_NAME

	Options:
	  --memory <MEM>				sets guest RAM size to MEM (default: $default_memory)
	  --cores <NUM>					sets the number of CPUs to NUM (default: $default_cores)
	  --kvm						enable hardware accelaration using KVM
	  --cpu <CPU>					emulate selected CPU
	  --replace					first delete VM with this name if it already exists
	  --iso-path <path>				attach the ISO at this path to the VM as cdrom
	  --iso-url <URL>				attach the ISO at this url to the VM as cdrom
	  --create-boot-drive				create empty qcow2 file as boot drive for the VM
	  --disk-size <GB>				allocate this much disk space for the boot drive (default: $default_disk_size)
	  --boot-drive-url <URL>			use file at this url as boot image (default: $default_boot_drive_url)
	  --boot-drive-path <path>			use local file at this path as boot image (mutually exclusive with --boot-drive-url)
	  --force-download				download URL images even if already cached (VMs created from the old image may break)
	  --boot-drive-format <FORMAT>			file format of boot image: qcow2 or raw (default: autodetect with qemu-img info)
	  --drive <path>					attach an existing disk image (repeatable)
	  --new-drive <size>				create and attach an empty qcow2 drive (repeatable)
	  --net <user | tap=IFNAME>			add a network card (repeatable; default: one user card with ssh port forwarding)
	  --net-address-cidr <IP-CIDR>			set static address for the previously added card (tap only)
	  --net-gateway <IP>				set default gateway for the previously added card (tap only)
	  --net-dhcp					use dhcp on the previously added card (tap only)
	  --cloud-init-network-config-version <VERSION>	use specified network-config version (1 or 2, default: 2)
	  --spice					enable and connect to SPICE
	  --gtk						use gtk GUI for VM output
	  --vnc <number>				enable and start vnc server on port 5900+<number>
	  --no-cloud-init-drive				don't attach cloud-init drive for NoCloud datasource
	  --cloud-init-user-data <path>			use this file as cloud-init user-data
	  --log-serial					redirect serial port to a file
	  --uefi					use UEFI (OVMF) instead of legacy BIOS (SeaBIOS)
	  --uefi-empty-varstore				use empty OVMF_VARS file (no secure boot keys enrolled)
	  --tpm						enable TPM 2.0 emulation using swtpm
	  --guest-agent					enable qemu guest agent support for this VM
	  --kernel <PATH>				boot the kernel at PATH directly
	  --initramfs <PATH>				use initramfs at PATH when direct kernel booting
	  --append-cmdline <CMDLINE>			use CMDLINE as the kernel command line
	  --gdb						enable gdb server
	  --dry-run					print qemu command, which would be run, but don't actually run qemu
	  -v, --verbose					print executed commands
	  -h, --help					show help and exit
	EOF
}

fetch()
{
	url=$1
	dest=$2
	tmp="$dest.partial"
	curl "$url" --output "$tmp" --fail --location || { rm -f "$tmp"; fatal "Failed to download '$url'"; }
	mv "$tmp" "$dest"
}

# assign $2 to the variable named $1, safe for arbitrary values
set_var()
{
	eval "$1=\"\$2\""
}

# write a shell-quoted key=value line to stdout (grouped into vmm.conf below)
config_write()
{
	printf "%s='%s'\n" "$1" "$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"
}

vm_name=
verbose=0
memory=
cores=
enable_kvm=0
cpu=
replace=0
iso_path_option=
iso_url=
force_download=0
create_boot_drive=0
disk_size=
boot_drive_url=
boot_drive_path_option=
boot_drive_format=
drive_count=0
netif_count=0
cloud_init_network_config_version=2
enable_spice=0
display_gtk=0
vnc=
attach_cloud_init_drive=1
log_serial=0
uefi=0
uefi_empty_varstore=0
enable_tpm=0
enable_qemu_guest_agent=0
kernel_path=
initramfs_path=
append_cmdline=
enable_gdb=0
cloud_init_user_data_path=
dry_run=0
while true; do
	case "$1" in
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	--memory)
		memory="$2"
		shift 2
		;;
	--cores)
		cores="$2"
		shift 2
		;;
	--kvm)
		enable_kvm=1
		shift
		;;
	--cpu)
		cpu="$2"
		shift 2
		;;
	--replace)
		replace=1
		shift
		;;
	--iso-path)
		iso_path_option="$2"
		shift 2
		;;
	--iso-url)
		iso_url="$2"
		shift 2
		;;
	--force-download)
		force_download=1
		shift
		;;
	--create-boot-drive)
		create_boot_drive=1
		shift
		;;
	--disk-size)
		disk_size="$2"
		shift 2
		;;
	--boot-drive-url)
		boot_drive_url="$2"
		shift 2
		;;
	--boot-drive-path)
		boot_drive_path_option="$2"
		shift 2
		;;
	--boot-drive-format)
		boot_drive_format="$2"
		shift 2
		;;
	--drive)
		[ "$#" -ge 2 ] || fatal 'Not enough arguments: --drive'
		set_var "drive_${drive_count}_path" "$2"
		drive_count=$((drive_count + 1))
		shift 2
		;;
	--new-drive)
		[ "$#" -ge 2 ] || fatal 'Not enough arguments: --new-drive'
		set_var "drive_${drive_count}_new_size" "$2"
		drive_count=$((drive_count + 1))
		shift 2
		;;
	--net)
		[ "$#" -ge 2 ] || fatal 'Not enough arguments: --net'
		case "$2" in
			user)
				set_var "netif_${netif_count}_type" user
				;;
			tap=*)
				set_var "netif_${netif_count}_type" tap
				set_var "netif_${netif_count}_ifname" "${2#tap=}"
				;;
			*)
				fatal "unknown network card type '$2' (want 'user' or 'tap=<ifname>')"
				;;
		esac
		netif_count=$((netif_count + 1))
		shift 2
		;;
	--net-address-cidr)
		[ "$#" -ge 2 ] || fatal 'Not enough arguments: --net-address-cidr'
		[ "$netif_count" -gt 0 ] || fatal '--net-address-cidr requires a preceding --net'
		set_var "netif_$((netif_count - 1))_address_cidr" "$2"
		shift 2
		;;
	--net-gateway)
		[ "$#" -ge 2 ] || fatal 'Not enough arguments: --net-gateway'
		[ "$netif_count" -gt 0 ] || fatal '--net-gateway requires a preceding --net'
		set_var "netif_$((netif_count - 1))_gateway" "$2"
		shift 2
		;;
	--net-dhcp)
		[ "$netif_count" -gt 0 ] || fatal '--net-dhcp requires a preceding --net'
		set_var "netif_$((netif_count - 1))_dhcp" 1
		shift
		;;
	--cloud-init-network-config-version)
		cloud_init_network_config_version="$2"
		shift 2
		;;
	--spice)
		enable_spice=1
		shift
		;;
	--gtk)
		display_gtk=1
		shift
		;;
       --vnc)
               vnc="$2"
               shift 2
               ;;
	--no-cloud-init-drive)
		attach_cloud_init_drive=0
		shift
		;;
	--log-serial)
		log_serial=1
		shift
		;;
	--uefi)
		uefi=1
		shift
		;;
	--uefi-empty-varstore)
		uefi_empty_varstore=1
		shift
		;;
	--tpm)
		enable_tpm=1
		shift
		;;
	--guest-agent)
		enable_qemu_guest_agent=1
		shift
		;;
	--kernel)
		kernel_path="$2"
		shift 2
		;;
	--initramfs)
		initramfs_path="$2"
		shift 2
		;;
	--append-cmdline)
		append_cmdline="$2"
		shift 2
		;;
	--gdb)
		enable_gdb=1
		shift
		;;
	--cloud-init-user-data)
		cloud_init_user_data_path="$2"
		shift 2
		;;
	--dry-run)
		dry_run=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

if [ -n "$boot_drive_path_option" ] && [ -n "$boot_drive_url" ]; then
	fatal '--boot-drive-path and --boot-drive-url are mutually exclusive'
fi

if [ "$create_boot_drive" -eq 1 ] && { [ -n "$boot_drive_path_option" ] || [ -n "$boot_drive_url" ]; }; then
	fatal '--create-boot-drive cannot be combined with a boot drive image'
fi

[ -z "$boot_drive_path_option" ] || boot_drive_path_option=$(abspath "$boot_drive_path_option")
[ -z "$iso_path_option" ] || iso_path_option=$(abspath "$iso_path_option")

[ -n "$boot_drive_url" ] || boot_drive_url="$default_boot_drive_url"
[ -n "$memory" ] || memory="$default_memory"
[ -n "$cores" ] || cores="$default_cores"
[ -n "$disk_size" ] || disk_size="$default_disk_size"

# default: one user-mode card with ssh forwarding
if [ "$netif_count" -eq 0 ]; then
	netif_count=1
	set_var netif_0_type user
fi

gateway_count=0
i=0
while [ "$i" -lt "$netif_count" ]; do
	netif_type=$(get_var "netif_${i}_type"); netif_dhcp=$(get_var "netif_${i}_dhcp")
	netif_cidr=$(get_var "netif_${i}_address_cidr"); netif_gateway=$(get_var "netif_${i}_gateway")

	if [ "$netif_type" = 'user' ]; then
		[ -z "$netif_cidr" ] || fatal 'user networking does not support --net-address-cidr'
		[ -z "$netif_gateway" ] || fatal 'user networking does not support --net-gateway'
	elif [ -n "$netif_dhcp" ]; then
		[ -z "$netif_cidr" ] || fatal '--net-dhcp and --net-address-cidr are mutually exclusive'
		[ -z "$netif_gateway" ] || fatal '--net-dhcp and --net-gateway are mutually exclusive'
	else
		[ -n "$netif_cidr" ] || fatal '--net tap requires --net-address-cidr or --net-dhcp'
		[ -n "$netif_gateway" ] || fatal '--net-address-cidr requires --net-gateway'
	fi
	[ -z "$netif_gateway" ] || gateway_count=$((gateway_count + 1))

	i=$((i + 1))
done
[ "$gateway_count" -le 1 ] || fatal 'only one network card can have a gateway'

# normalize to qemu display syntax (":N" listens on port 5900+N)
if [ -n "$vnc" ]; then
	case "$vnc" in
		*:*) ;;
		*) vnc=":$vnc" ;;
	esac
fi

vm_dir="$vmm_dir/$vm_name"
vm_config_path="$vm_dir/vmm.conf"
monitor_socket_path="$vm_dir/monitor.socket"

if [ -d "$vm_dir" ]; then
	[ "$replace" -eq 1 ] || fatal "VM '$vm_name' already exists"

	if [ -S "$monitor_socket_path" ]; then
		qmp "$monitor_socket_path" '{"execute": "quit"}' > /dev/null
		wait_qemu_exit "$vm_dir"
	fi

	rm -rf "$vm_dir"
fi

mkdir -p "$vm_dir"

# remove the half-created VM if anything below fails
vm_dir_incomplete=1
cleanup_on_exit()
{
	[ "$vm_dir_incomplete" -eq 0 ] || rm -rf "$vm_dir"
}
trap cleanup_on_exit EXIT
trap 'exit 1' HUP INT TERM

vm_disk_path="$vm_dir/disk"
vm_cloud_init_dir="$vm_dir/cloud-init"
vm_cloud_init_drive_path="$vm_cloud_init_dir/cloud_init_drive.img"

mkdir -p "$images_dir" "$iso_dir"

if [ -n "$boot_drive_path_option" ]; then
	boot_drive_path=$boot_drive_path_option
	[ -f "$boot_drive_path" ] || fatal "Boot drive image '$boot_drive_path' doesn't exist"
else
	boot_drive_path="$images_dir/${boot_drive_url##*/}"
fi

if [ -n "$iso_path_option" ]; then
	iso_path=$iso_path_option
elif [ -n "$iso_url" ]; then
	iso_path=$iso_dir/${iso_url##*/}
fi

if [ "$create_boot_drive" -eq 0 ] && [ -z "$boot_drive_path_option" ]; then
	if [ "$force_download" -eq 1 ] || [ ! -f "$boot_drive_path" ]; then
		echo "Downloading boot drive image from '$boot_drive_url'" >&2
		fetch "$boot_drive_url" "$boot_drive_path"
	fi
fi

if [ -n "$iso_url" ]; then
	if [ "$force_download" -eq 1 ] || [ ! -f "$iso_path" ]; then
		echo "Downloading ISO from '$iso_url'" >&2
		fetch "$iso_url" "$iso_path"
	fi
fi

# xz-compressed images are decompressed into the cache once and reused
if [ "$create_boot_drive" -eq 0 ]; then
	case "$boot_drive_path" in
		*.xz)
			decompressed=${boot_drive_path%.xz}
			decompressed="$images_dir/${decompressed##*/}"
			if [ "$force_download" -eq 1 ] || [ ! -f "$decompressed" ]; then
				echo "Decompressing '$boot_drive_path'" >&2
				xz -dc "$boot_drive_path" > "$decompressed.tmp" || { rm -f "$decompressed.tmp"; fatal "Failed to decompress '$boot_drive_path'"; }
				mv "$decompressed.tmp" "$decompressed"
			fi
			boot_drive_path=$decompressed
			;;
	esac
fi

if [ "$create_boot_drive" -eq 0 ] && [ -z "$boot_drive_format" ]; then
	boot_drive_format=$(qemu-img info --output=json "$boot_drive_path" 2> /dev/null | jq -r .format)
	case "$boot_drive_format" in
		qcow2 | raw) ;;
		'') fatal "Failed to detect the format of '$boot_drive_path' (not a disk image?)" ;;
		*) fatal "Unsupported boot drive format '$boot_drive_format' of '$boot_drive_path' (convert to qcow2 or raw first)" ;;
	esac
fi

if [ "$create_boot_drive" -eq 0 ]; then
	if [ "$boot_drive_format" = 'qcow2' ]; then
		qemu-img create -b "$boot_drive_path" -B "$boot_drive_format" -f "$boot_drive_format" "$vm_disk_path" "$disk_size" > /dev/null || fatal "Failed to create a boot drive for '$vm_name' from '$boot_drive_url'"
	elif [ "$boot_drive_format" = 'raw' ]; then
		vm_disk_path=$vm_disk_path.raw
		cp -a "$boot_drive_path" "$vm_disk_path" > /dev/null || fatal "Failed to copy the boot drive image for '$vm_name' from '$boot_drive_path'"
		qemu-img resize "$vm_disk_path" "$disk_size" || fatal "Failed to resize the boot drive '$vm_disk_path' to '$disk_size'"
	else
		fatal "Unknown boot drive file format '$boot_drive_format'"
	fi
else
	qemu-img create -f qcow2 "$vm_disk_path" "$disk_size" > /dev/null || fatal "Failed to create a new empty boot drive for '$vm_name'"
	boot_drive_format=qcow2
fi

i=0
while [ "$i" -lt "$drive_count" ]; do
	drive_path=$(get_var "drive_${i}_path"); drive_new_size=$(get_var "drive_${i}_new_size")

	if [ -n "$drive_new_size" ]; then
		drive_path="$vm_dir/disk$((i + 2)).qcow2"
		qemu-img create -f qcow2 "$drive_path" "$drive_new_size" > /dev/null || fatal "Failed to create drive '$drive_path'"
		set_var "drive_${i}_path" "$drive_path"
		drive_format=qcow2
	else
		drive_path=$(abspath "$drive_path")
		[ -f "$drive_path" ] || fatal "Drive image '$drive_path' doesn't exist"
		set_var "drive_${i}_path" "$drive_path"
		drive_format=$(qemu-img info --output=json "$drive_path" 2> /dev/null | jq -r .format)
		[ -n "$drive_format" ] || fatal "Failed to detect the format of drive '$drive_path' (not a disk image?)"
	fi
	set_var "drive_${i}_format" "$drive_format"

	i=$((i + 1))
done

next_ssh_port=24000
ssh_port=
any_tap=0
i=0
while [ "$i" -lt "$netif_count" ]; do
	netif_type=$(get_var "netif_${i}_type")

	mac=$(printf '%s' "$vm_name:$i" | crc32 /dev/stdin | sed -E 's/.*(.{2})(.{2})(.{2})$/52:54:00:\1:\2:\3/')
	set_var "netif_${i}_mac" "$mac"

	if [ "$netif_type" = 'user' ]; then
		while [ "$(ss --no-header --tcp state all sport "$next_ssh_port" | wc -l)" -ne 0 ]; do
			next_ssh_port=$((next_ssh_port + 1))
		done
		set_var "netif_${i}_ssh_port" "$next_ssh_port"
		: "${ssh_port:=$next_ssh_port}"
		next_ssh_port=$((next_ssh_port + 1))
	else
		any_tap=1
	fi

	i=$((i + 1))
done

if [ "$attach_cloud_init_drive" -eq 1 ]; then
	mkdir -p "$vm_cloud_init_dir"

	ssh_key_path="$vm_dir/id_ed25519"

	ssh-keygen -t ed25519 -f "$ssh_key_path" -N '' > /dev/null || fatal "Failed to generate an ssh key for '$vm_name'"

	pub_ssh_key_path="${ssh_key_path}.pub"
	pub_ssh_key="$(cat "$pub_ssh_key_path")"

	user_data_path="$vm_cloud_init_dir/user-data"

	if [ -n "$cloud_init_user_data_path" ]; then
		cp -a "$cloud_init_user_data_path" "$user_data_path" || fatal "Failed to copy user-data from '$cloud_init_user_data_path'"
	else
		cat <<-EOF > "$user_data_path"
		#cloud-config
		disable_root: false
		users:
		  - name: root
		    lock_passwd: false
		    plain_text_passwd: "123"
		    ssh_authorized_keys:
		      - ${pub_ssh_key}
		hostname: ${vm_name}
		EOF
	fi

	if [ "$any_tap" -eq 0 ]; then
		cloud-localds --hostname "$vm_name" "$vm_cloud_init_drive_path" "$user_data_path" || fatal "Failed to create the cloud-init drive for '$vm_name'"
	else
		network_config_path="$vm_cloud_init_dir/network-config"

		case "$cloud_init_network_config_version" in
			2)
				{
					echo 'version: 2'
					echo 'ethernets:'
					i=0
					while [ "$i" -lt "$netif_count" ]; do
						netif_type=$(get_var "netif_${i}_type"); netif_mac=$(get_var "netif_${i}_mac")
					netif_dhcp=$(get_var "netif_${i}_dhcp")
					netif_cidr=$(get_var "netif_${i}_address_cidr"); netif_gateway=$(get_var "netif_${i}_gateway")

						echo "  nic$i:"
						echo '    match:'
						echo "      macaddress: \"$netif_mac\""
						if [ "$netif_type" = 'user' ] || [ -n "$netif_dhcp" ]; then
							echo '    dhcp4: true'
						else
							echo '    addresses:'
							echo "      - $netif_cidr"
							echo '    routes:'
							echo '      - to: 0.0.0.0/0'
							echo "        via: $netif_gateway"
							echo '    nameservers:'
							echo '      addresses:'
							echo '        - 8.8.8.8'
						fi

						i=$((i + 1))
					done
				} > "$network_config_path"
				;;
			1)
				{
					echo 'version: 1'
					echo 'config:'
					i=0
					while [ "$i" -lt "$netif_count" ]; do
						netif_type=$(get_var "netif_${i}_type"); netif_mac=$(get_var "netif_${i}_mac")
					netif_dhcp=$(get_var "netif_${i}_dhcp")
					netif_cidr=$(get_var "netif_${i}_address_cidr"); netif_gateway=$(get_var "netif_${i}_gateway")

						echo '  - type: physical'
						echo "    name: eth$i"
						echo "    mac_address: \"$netif_mac\""
						echo '    subnets:'
						if [ "$netif_type" = 'user' ] || [ -n "$netif_dhcp" ]; then
							echo '      - type: dhcp'
						else
							echo '      - type: static'
							echo "        address: $netif_cidr"
							echo "        gateway: $netif_gateway"
							echo '        dns_nameservers:'
							echo '          - 8.8.8.8'
						fi

						i=$((i + 1))
					done
				} > "$network_config_path"
				;;
			*)
				fatal "unknown cloud-init network-config version: '$cloud_init_network_config_version'"
				;;
		esac

		cloud-localds --hostname "$vm_name" --network-config "$network_config_path" "$vm_cloud_init_drive_path" "$user_data_path" || fatal "Failed to create the cloud-init drive for '$vm_name'"
	fi
fi

vm_uuid="$(uuidgen)"

{
	config_write vm_uuid "$vm_uuid"
	config_write vm_disk_path "$vm_disk_path"
	config_write boot_drive_format "$boot_drive_format"
	config_write memory "$memory"
	config_write cores "$cores"
	config_write kvm "$enable_kvm"
	config_write cpu "$cpu"
	config_write vnc "$vnc"
	config_write ssh_port "$ssh_port"
	config_write netif_count "$netif_count"
	i=0
	while [ "$i" -lt "$netif_count" ]; do
		config_write netif_${i}_type "$(get_var "netif_${i}_type")"
		config_write netif_${i}_ifname "$(get_var "netif_${i}_ifname")"
		config_write netif_${i}_mac "$(get_var "netif_${i}_mac")"
		config_write netif_${i}_ssh_port "$(get_var "netif_${i}_ssh_port")"
		config_write netif_${i}_address_cidr "$(get_var "netif_${i}_address_cidr")"
		i=$((i + 1))
	done
	config_write attach_cloud_init_drive "$attach_cloud_init_drive"
	config_write drive_count "$drive_count"
	i=0
	while [ "$i" -lt "$drive_count" ]; do
		config_write drive_${i}_path "$(get_var "drive_${i}_path")"
		config_write drive_${i}_format "$(get_var "drive_${i}_format")"
		i=$((i + 1))
	done
	config_write enable_spice "$enable_spice"
	config_write log_serial "$log_serial"
	config_write uefi "$uefi"
	config_write enable_tpm "$enable_tpm"
	config_write enable_qemu_guest_agent "$enable_qemu_guest_agent"
	config_write kernel_path "$kernel_path"
	config_write initramfs_path "$initramfs_path"
	config_write append_cmdline "$append_cmdline"
	config_write enable_gdb "$enable_gdb"
} > "$vm_config_path"

# the OVMF varstore is per-VM state and must be created here; everything
# else launch-related is handled by svmm-start from vmm.conf
if [ "$uefi" -eq 1 ]; then
	if [ "$uefi_empty_varstore" -eq 1 ]; then
		cp -a "$ovmf_dir/OVMF_VARS_4M.qcow2" "$vm_dir/OVMF_VARS_4M.qcow2" || fatal 'Failed to copy the OVMF varstore (is OVMF installed?)'
	else
		cp -a "$ovmf_dir/OVMF_VARS_4M.secboot.qcow2" "$vm_dir/OVMF_VARS_4M.qcow2" || fatal 'Failed to copy the OVMF varstore (is OVMF installed?)'
	fi
fi

set --
[ -z "$iso_path" ] || set -- "$@" --iso-path "$iso_path"
[ "$display_gtk" -eq 0 ] || set -- "$@" --gtk
[ "$dry_run" -eq 0 ] || set -- "$@" --dry-run
[ "$verbose" -eq 0 ] || set -- "$@" --verbose

# creation succeeded: keep the VM directory even if the start fails
vm_dir_incomplete=0

exec svmm-start "$@" "$vm_name"
