#!/usr/bin/env sh

set -f

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

show_help()
{
	cat <<-EOF
	svmm-ssh [options] VM_NAME

	Options:
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

vm_name=
verbose=0
while true; do
	case "$1" in
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

vm_dir="$vmm_dir/$vm_name"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"

. "$vm_dir/vmm.conf"

if [ -n "$ssh_port" ]; then
	set -- -p "$ssh_port" root@127.0.0.1
else
	# no forwarded ssh port: use the first tap NIC with a known address,
	# either the configured static one or a lease from svmm-dnsmasq
	ip=
	i=0
	while [ "$i" -lt "${netif_count:-0}" ] && [ -z "$ip" ]; do
		if [ "$(get_var "netif_${i}_type")" = 'tap' ]; then
			cidr=$(get_var "netif_${i}_address_cidr")
			if [ -n "$cidr" ]; then
				ip=${cidr%/*}
			elif [ -f "$dnsmasq_leases_file" ]; then
				mac=$(get_var "netif_${i}_mac")
				ip=$(awk -v mac="$mac" '$2 == mac {print $3}' "$dnsmasq_leases_file" | tail -n 1)
			fi
		fi
		i=$((i + 1))
	done
	[ -n "$ip" ] || fatal "VM '$vm_name' has no forwarded ssh port and no known tap NIC address"
	set -- "root@$ip"
fi

ssh -i "$vm_dir/id_ed25519" -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$@"
