#!/usr/bin/env sh

set -f

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

show_help()
{
	cat <<-EOF
	svmm-stop [options] VM_NAME

	Options:
	  -f, --force			forcefully quit the VM
	  -w, --wait			wait until the qemu process is stopped
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

vm_name=
force=0
wait=0
verbose=0
while true; do
	case "$1" in
	-v | --verbose)
		verbose=1
		shift
		;;
	-h | --help)
		show_help
		exit 0
		;;
	-f | --force)
		force=1
		shift
		;;
	-w | --wait)
		wait=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

vm_dir="$vmm_dir/$vm_name"
monitor_socket_path="$vm_dir/monitor.socket"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"
[ -S "$monitor_socket_path" ] || fatal "VM '$vm_name' is not running"

if [ "$force" -eq 1 ]; then
	qmp "$monitor_socket_path" '{"execute": "quit"}' > /dev/null
else
	qmp "$monitor_socket_path" '{"execute": "system_powerdown"}' > /dev/null
fi

[ "$wait" -eq 1 ] || exit 0

wait_qemu_exit "$vm_dir"
