#!/usr/bin/env sh

set -f

PROG="${0##*/}"

vmm_dir="$HOME/vmm"

show_help()
{
	cat <<-EOF
	svmm-start [options] VM_NAME

	Options:
	  --iso-path <path>		attach the ISO at this path to the VM as cdrom
	  -h, --help			show help and exit
	EOF
}

fatal()
{
	printf '%s: %s\n' "$PROG" "$1" >&2
	exit 1
}

vm_name=
iso_path=
while true; do
	case "$1" in
	--iso-path)
		iso_path="$2"
		shift 2
		;;
	-h | --help)
		show_help
		exit 0
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

vm_dir="$vmm_dir/$vm_name"
monitor_socket_path="$vm_dir/monitor.socket"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"

vm_disk_path="$vm_dir/disk.qcow2"
vm_config_path="$vm_dir/vmm.conf"

. "$vm_config_path"


set -- -name "$vm_name" \
	-accel kvm \
	-cpu host \
	-m 2G \
	-smp 2 \
	-display none \
	-daemonize \
	-smbios "type=1,uuid=$vm_uuid" \
	-monitor "unix:${monitor_socket_path},server=on,wait=off" \
	-blockdev "node-name=disk1,discard=unmap,driver=qcow2,file.driver=file,file.filename=${vm_disk_path}" \
	-device virtio-blk-pci,drive=disk1

if [ -n "$iso_path" ]; then
	set -- "$@" -blockdev "node-name=cdrom1,read-only=on,force-share=on,driver=raw,file.driver=file,file.filename=$iso_path" \
		-device ide-cd,drive=cdrom1
fi

if [ "${attach_cloud_init_drive:?}" -eq 1 ]; then
	vm_cloud_init_drive_path="$vm_dir/cloud_init_drive.img"
	set -- "$@" -blockdev "node-name=cloud-init-drive,read-only=on,force-share=on,driver=raw,file.driver=file,file.filename=${vm_cloud_init_drive_path}" \
		-device virtio-blk-pci,drive=cloud-init-drive
fi

if [ -n "${second_drive}" ]; then
	set -- "$@" -blockdev "node-name=disk2,discard=unmap,driver=qcow2,file.driver=file,file.filename=${second_drive:?}" \
		-device virtio-blk-pci,drive=disk2
fi

if [ "${network_type:?}" = 'user' ]; then
	set -- "$@" -netdev "user,id=net0,hostfwd=tcp:127.0.0.1:${ssh_port:?}-:22" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address:?}"
fi

if [ "${network_type:?}" = 'tap' ]; then
	set -- "$@" -netdev "tap,id=net0,ifname=${network_tap_device_name:?},script=no" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address:?}"
fi

if [ "${enable_spice:?}" -eq 1 ]; then
	set -- "$@" -display spice-app
fi

if [ "${log_serial:?}" -eq 1 ]; then
	qemu_serial_log_path="$vm_dir/serial.log"
	if [ -f "$qemu_serial_log_path" ]; then
		existing_logs=0
		for file in "$qemu_serial_log_path".[0-9][0-9]; do
		    if [ -e "$file" ]; then
			existing_logs="$((existing_logs + 1))"
		    fi
		done
	fi
	set -- "$@" -serial "file:$qemu_serial_log_path.$((existing_logs + 1))"
fi

qemu-system-x86_64 "$@"
