#!/usr/bin/env sh

set -f

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

ovmf_dir='/usr/share/OVMF'

show_help()
{
	cat <<-EOF
	svmm-start [options] VM_NAME

	Options:
	  --iso-path <path>		attach the ISO at this path to the VM as cdrom
	  --gtk				use gtk GUI for VM output
	  --dry-run			print qemu command, which would be run, but don't actually run qemu
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

vm_name=
iso_path=
verbose=0
display_gtk=0
dry_run=0
while true; do
	case "$1" in
	--iso-path)
		iso_path="$2"
		shift 2
		;;
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	--gtk)
		display_gtk=1
		shift
		;;
	--dry-run)
		dry_run=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

[ -z "$iso_path" ] || iso_path=$(abspath "$iso_path")

vm_dir="$vmm_dir/$vm_name"
monitor_socket_path="$vm_dir/monitor.socket"
qemu_pid_file_path="$vm_dir/qemu_pid"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"

svmm-is-qemu-running "$vm_name" && fatal "VM '$vm_name' is already running"

vm_cloud_init_dir="$vm_dir/cloud-init"
vm_config_path="$vm_dir/vmm.conf"

. "$vm_config_path"


set -- -name "$vm_name" \
	-m "${memory:?}" \
	-smp "${cores:?}" \
	-daemonize \
	-nodefaults \
	-pidfile "$qemu_pid_file_path" \
	-smbios "type=1,uuid=${vm_uuid:?}" \
	-chardev "socket,id=qmp,path=${monitor_socket_path},server=on,wait=off" \
	-mon chardev=qmp,mode=control,pretty=off \
	-blockdev "node-name=disk1,discard=unmap,driver=${boot_drive_format:?},file.driver=file,file.filename=${vm_disk_path:?}" \
	-device virtio-blk-pci,drive=disk1,bootindex=0

if [ "${kvm:?}" -eq 1 ]; then
	set -- "$@" -accel kvm
fi

if [ -n "$cpu" ]; then
	set -- "$@" -cpu "$cpu"
fi

if [ -n "$vnc" ]; then
	set -- "$@" -vnc "$vnc"
fi

if [ -n "$iso_path" ]; then
	set -- "$@" -blockdev "node-name=cdrom1-drive,read-only=on,force-share=on,driver=raw,file.driver=file,file.filename=$iso_path" \
		-device ide-cd,id=cdrom1,drive=cdrom1-drive,bootindex=1
fi

if [ "${attach_cloud_init_drive:?}" -eq 1 ]; then
	vm_cloud_init_drive_path="$vm_cloud_init_dir/cloud_init_drive.img"
	set -- "$@" -blockdev "node-name=cloud-init-drive,read-only=on,force-share=on,driver=raw,file.driver=file,file.filename=${vm_cloud_init_drive_path}" \
		-device virtio-blk-pci,drive=cloud-init-drive
fi

i=0
while [ "$i" -lt "${drive_count:-0}" ]; do
	eval "drive_path=\$drive_${i}_path; drive_format=\$drive_${i}_format"
	set -- "$@" -blockdev "node-name=disk$((i + 2)),discard=unmap,driver=${drive_format},file.driver=file,file.filename=${drive_path}" \
		-device virtio-blk-pci,drive=disk$((i + 2))
	i=$((i + 1))
done

if [ "${network_type:?}" = 'user' ]; then
	set -- "$@" -netdev "user,id=net0,hostfwd=tcp:127.0.0.1:${ssh_port:?}-:22" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address:?}"
fi

if [ "${network_type:?}" = 'tap' ]; then
	set -- "$@" -netdev "tap,id=net0,ifname=${network_tap_device_name:?},script=no" \
		-device "virtio-net-pci,netdev=net0,mac=${vm_mac_address:?}"
fi

if [ "${enable_spice:?}" -eq 1 ]; then
	set -- "$@" -display spice-app
elif [ "$display_gtk" -eq 1 ]; then
	set -- "$@" -display gtk -device VGA
else
	set -- "$@" -display none
fi

if [ "${log_serial:?}" -eq 1 ]; then
	qemu_serial_log_path="$vm_dir/serial-$(date +%Y%m%d-%H%M%S).log"
	set -- "$@" -serial "file:$qemu_serial_log_path"
fi

if [ "${enable_tpm:?}" -eq 1 ]; then
	mkdir -p "$XDG_RUNTIME_DIR/swtpm"
	mkdir -p "$vm_dir/tpm2"
	swtpm socket \
		--ctrl "type=unixio,path=$XDG_RUNTIME_DIR/swtpm/$vm_name-swtpm.sock,mode=0600" \
		--tpmstate "dir=$vm_dir/tpm2,mode=0600,lock" \
		--log "file=$vm_dir/$vm_name-swtpm.log" \
		--terminate \
		--tpm2 &

	set -- "$@" -chardev "socket,id=chrtpm,path=$XDG_RUNTIME_DIR/swtpm/$vm_name-swtpm.sock" \
		-tpmdev emulator,id=tpm0,chardev=chrtpm \
		-device tpm-crb,tpmdev=tpm0
fi

if [ "${enable_qemu_guest_agent:?}" -eq 1 ]; then
	set -- "$@" -chardev "socket,path=$vm_dir/qemu_guest_agent.sock,server=on,wait=off,id=qga0" \
		-device virtio-serial \
		-device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0
fi

if [ "${uefi:?}" -eq 1 ]; then
	set -- "$@" -machine q35 \
		-drive "if=pflash,format=qcow2,readonly=on,file=$ovmf_dir/OVMF_CODE_4M.secboot.qcow2" \
		-drive "if=pflash,format=qcow2,file=$vm_dir/OVMF_VARS_4M.qcow2"
fi

if [ -n "$kernel_path" ]; then
	set -- "$@" -kernel "$kernel_path"
	[ -z "$initramfs_path" ] || set -- "$@" -initrd "$initramfs_path"
	[ -z "$append_cmdline" ] || set -- "$@" -append "$append_cmdline"
fi

if [ "${enable_gdb:-0}" -eq 1 ]; then
	set -- "$@" -s -S
fi

if [ "$dry_run" -eq 1 ]; then
	echo qemu-system-x86_64 "$@"
else
	qemu-system-x86_64 "$@"
fi
