#!/usr/bin/env sh

PROG="${0##*/}"

vmm_dir="$HOME/vmm"

show_help()
{
	cat <<-EOF
	svmm-list [options]

	Options:
	  -h, --help			show help and exit
	  -v, --verbose			print executed commands
	EOF
}

fatal()
{
	printf '%s: %s\n' "$PROG" "$1" >&2
	exit 1
}

verbose=0
while true; do
	case "$1" in
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		break
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

for vm_dir in "$vmm_dir"/*; do
	printf '%s\t' "${vm_dir##*/}"
	if [ -S "$vm_dir/monitor.socket" ]; then
		echo "Running"
	else
		echo "Stopped"
	fi
done
