#!/usr/bin/env sh

set -f

PROG="${0##*/}"

vmm_dir="$HOME/vmm"

show_help()
{
	cat <<-EOF
	svmm-monitor [options] COMMAND VM_NAME

	Commands:
	  raw				connect to monitor socket to issue raw requests
	  query-block			query info about block devices
	  eject <DEVICE_ID>		eject device with id DEVICE_ID
	  change <DEVICE_ID> <FILENAME>	change device with id DEVICE_ID to FILENAME

	Options:
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

fatal()
{
	printf '%s: %s\n' "$PROG" "$1" >&2
	exit 1
}

verbose=0
command=
vm_name=
device_id=
filename=
while true; do
	case "$1" in
	-v | --verbose)
		verbose=1
		shift
		;;
	-h | --help)
		show_help
		exit 0
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	raw)
		command=raw
		shift
		;;
	query-block)
		command=query-block
		shift
		;;
	eject)
		command=eject
		shift
		if [ -n "$1" ]; then
			device_id="$1"
			shift
		else
			fatal 'device id to eject is not specified'
		fi
		;;
	change)
		command=change
		shift
		if [ -n "$1" ] && [ -n "$2" ]; then
			device_id="$1"
			filename="$2"
			shift 2
		else
			fatal 'device id to change or filename are not specified'
		fi
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$command" ] || fatal 'COMMAND is not specified'
[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

vm_dir="$vmm_dir/$vm_name"
monitor_socket_path="$vm_dir/monitor.socket"

[ -d "$vm_dir" ] || fatal "VM '$vm_name' doesn't exist"

[ -S "$monitor_socket_path" ] || fatal "monitor socket is not accessible for VM '$vm_name'"

if [ "$command" = 'raw' ]; then
	socat READLINE "UNIX-CONNECT:$monitor_socket_path"
	exit
fi

if [ "$command" = 'query-block' ]; then
	result=$({ echo '{"execute":"qmp_capabilities"}' && echo '{"execute":"query-block"}'; } | socat STDIO "UNIX-CONNECT:$monitor_socket_path")

	while read -r line; do
		case "$line" in
			*'"QMP"'*) continue ;;
			*'{"return": {}}'*) continue ;;
		esac

		printf '%s' "$line" | jq -r '.return[] | "\(.qdev) \(.inserted.image.filename)"'
	done <<STR
$result
STR
	exit
fi

if [ "$command" = 'eject' ]; then
	{ echo '{"execute":"qmp_capabilities"}' && echo '{"execute":"eject","arguments":{"id":"'"$device_id"'"}}'; } | socat STDIO "UNIX-CONNECT:$monitor_socket_path" > /dev/null
	exit
fi

if [ "$command" = 'change' ]; then
	{ echo '{"execute":"qmp_capabilities"}' && echo '{"execute":"blockdev-change-medium","arguments":{"id":"'"$device_id"'","filename":"'"$filename"'","format":"raw"}}'; } | socat STDIO "UNIX-CONNECT:$monitor_socket_path" > /dev/null
	exit
fi
