#!/usr/bin/env sh

set -f

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

ovmf_dir='/usr/share/OVMF'

images_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/images"
iso_dir="${XDG_DATA_HOME:-$HOME/.local/share}/vmm/iso"

default_boot_drive_url='https://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/x86_64/alt-sisyphus-cloud-x86_64.qcow2'
default_disk_size='10G'
default_memory='2G'
default_cores='2'

show_help()
{
	cat <<-EOF
	svmm-run [options] VM_NAME

	Options:
	  --memory <MEM>				sets guest RAM size to MEM (default: $default_memory)
	  --cores <NUM>					sets the number of CPUs to NUM (default: $default_cores)
	  --kvm						enable hardware accelaration using KVM
	  --cpu <CPU>					emulate selected CPU
	  --replace					first delete VM with this name if it already exists
	  --iso-path <path>				attach the ISO at this path to the VM as cdrom
	  --iso-url <URL>				attach the ISO at this url to the VM as cdrom
	  --create-boot-drive				create empty qcow2 file as boot drive for the VM
	  --disk-size <GB>				allocate this much disk space for the boot drive (default: $default_disk_size)
	  --boot-drive-url <URL>			use file at this url as boot image (default: $default_boot_drive_url)
	  --boot-drive-path <path>			use local file at this path as boot image (mutually exclusive with --boot-drive-url)
	  --boot-drive-format <FORMAT>			file format of boot image: qcow2 or raw (default: autodetect with qemu-img info)
	  --second-drive <path>				path to qcow2 file to attach another drive to the VM
	  --net-tap <tap>				use QEMU tap networking and connect VM's NIC to tap device with this name
	  --net-address-cidr <IP-CIDR>			assign this IP address and network mask to the VM's network interface
	  --net-gateway <IP>				use this IP as the default gateway in the VM
	  --net-dhcp					enable dhcp discovery in VM
	  --cloud-init-network-config-version <VERSION>	use specified network-config version (1 or 2, default: 2)
	  --spice					enable and connect to SPICE
	  --gtk						use gtk GUI for VM output
	  --vnc <number>				enable and start vnc server on port 5900+<number>
	  --no-cloud-init-drive				don't attach cloud-init drive for NoCloud datasource
	  --cloud-init-user-data <path>			use this file as cloud-init user-data
	  --log-serial					redirect serial port to a file
	  --uefi					use UEFI (OVMF) instead of legacy BIOS (SeaBIOS)
	  --uefi-empty-varstore				use empty OVMF_VARS file (no secure boot keys enrolled)
	  --tpm						enable TPM 2.0 emulation using swtpm
	  --guest-agent					enable qemu guest agent support for this VM
	  --kernel <PATH>				boot the kernel at PATH directly
	  --initramfs <PATH>				use initramfs at PATH when direct kernel booting
	  --append-cmdline <CMDLINE>			use CMDLINE as the kernel command line
	  --gdb						enable gdb server
	  --dry-run					print qemu command, which would be run, but don't actually run qemu
	  -v, --verbose					print executed commands
	  -h, --help					show help and exit
	EOF
}

fetch()
{
	url=$1
	dest=$2
	tmp="$dest.partial"
	curl "$url" --output "$tmp" --fail --location || { rm -f "$tmp"; fatal "Failed to download '$url'"; }
	mv "$tmp" "$dest"
}

# write a shell-quoted key=value line to stdout (grouped into vmm.conf below)
config_write()
{
	printf "%s='%s'\n" "$1" "$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"
}

vm_name=
verbose=0
memory=
cores=
enable_kvm=0
cpu=
replace=0
iso_path_option=
iso_url=
create_boot_drive=0
disk_size=
boot_drive_url=
boot_drive_path_option=
boot_drive_format=
second_drive=
network_tap_device_name=
network_vm_ip_address_cidr=
network_vm_default_gateway=
network_vm_dhcp=0
cloud_init_network_config_version=2
enable_spice=0
display_gtk=0
vnc=
attach_cloud_init_drive=1
log_serial=0
uefi=0
uefi_empty_varstore=0
enable_tpm=0
enable_qemu_guest_agent=0
kernel_path=
initramfs_path=
append_cmdline=
enable_gdb=0
cloud_init_user_data_path=
dry_run=0
while true; do
	case "$1" in
	-h | --help)
		show_help
		exit 0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	--memory)
		memory="$2"
		shift 2
		;;
	--cores)
		cores="$2"
		shift 2
		;;
	--kvm)
		enable_kvm=1
		shift
		;;
	--cpu)
		cpu="$2"
		shift 2
		;;
	--replace)
		replace=1
		shift
		;;
	--iso-path)
		iso_path_option="$2"
		shift 2
		;;
	--iso-url)
		iso_url="$2"
		shift 2
		;;
	--create-boot-drive)
		create_boot_drive=1
		shift
		;;
	--disk-size)
		disk_size="$2"
		shift 2
		;;
	--boot-drive-url)
		boot_drive_url="$2"
		shift 2
		;;
	--boot-drive-path)
		boot_drive_path_option="$2"
		shift 2
		;;
	--boot-drive-format)
		boot_drive_format="$2"
		shift 2
		;;
	--second-drive)
		second_drive="$2"
		shift 2
		;;
	--net-tap)
		network_tap_device_name="$2"
		shift 2
		;;
	--net-address-cidr)
		network_vm_ip_address_cidr="$2"
		shift 2
		;;
	--net-gateway)
		network_vm_default_gateway="$2"
		shift 2
		;;
	--net-dhcp)
		network_vm_dhcp=1
		shift
		;;
	--cloud-init-network-config-version)
		cloud_init_network_config_version="$2"
		shift 2
		;;
	--spice)
		enable_spice=1
		shift
		;;
	--gtk)
		display_gtk=1
		shift
		;;
       --vnc)
               vnc="$2"
               shift 2
               ;;
	--no-cloud-init-drive)
		attach_cloud_init_drive=0
		shift
		;;
	--log-serial)
		log_serial=1
		shift
		;;
	--uefi)
		uefi=1
		shift
		;;
	--uefi-empty-varstore)
		uefi_empty_varstore=1
		shift
		;;
	--tpm)
		enable_tpm=1
		shift
		;;
	--guest-agent)
		enable_qemu_guest_agent=1
		shift
		;;
	--kernel)
		kernel_path="$2"
		shift 2
		;;
	--initramfs)
		initramfs_path="$2"
		shift 2
		;;
	--append-cmdline)
		append_cmdline="$2"
		shift 2
		;;
	--gdb)
		enable_gdb=1
		shift
		;;
	--cloud-init-user-data)
		cloud_init_user_data_path="$2"
		shift 2
		;;
	--dry-run)
		dry_run=1
		shift
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		if [ -n "$1" ]; then
			vm_name="$1"
			shift
		else
			break
		fi
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

[ -n "$vm_name" ] || fatal 'VM_NAME is not specified'

if [ -n "$boot_drive_path_option" ] && [ -n "$boot_drive_url" ]; then
	fatal '--boot-drive-path and --boot-drive-url are mutually exclusive'
fi

if [ "$create_boot_drive" -eq 1 ] && { [ -n "$boot_drive_path_option" ] || [ -n "$boot_drive_url" ]; }; then
	fatal '--create-boot-drive cannot be combined with a boot drive image'
fi

[ -z "$boot_drive_path_option" ] || boot_drive_path_option=$(abspath "$boot_drive_path_option")
[ -z "$iso_path_option" ] || iso_path_option=$(abspath "$iso_path_option")

[ -n "$boot_drive_url" ] || boot_drive_url="$default_boot_drive_url"
[ -n "$memory" ] || memory="$default_memory"
[ -n "$cores" ] || cores="$default_cores"
[ -n "$disk_size" ] || disk_size="$default_disk_size"

if [ -z "$network_tap_device_name" ]; then
	[ "$network_vm_dhcp" -eq 0 ] || fatal '--net-dhcp requires --net-tap'
	[ -z "$network_vm_ip_address_cidr" ] || fatal '--net-address-cidr requires --net-tap'
	[ -z "$network_vm_default_gateway" ] || fatal '--net-gateway requires --net-tap'
fi

# normalize to qemu display syntax (":N" listens on port 5900+N)
if [ -n "$vnc" ]; then
	case "$vnc" in
		*:*) ;;
		*) vnc=":$vnc" ;;
	esac
fi

vm_dir="$vmm_dir/$vm_name"
vm_config_path="$vm_dir/vmm.conf"
monitor_socket_path="$vm_dir/monitor.socket"

if [ -d "$vm_dir" ]; then
	[ "$replace" -eq 1 ] || fatal "VM '$vm_name' already exists"

	if [ -S "$monitor_socket_path" ]; then
		qmp "$monitor_socket_path" '{"execute": "quit"}' > /dev/null
		wait_qemu_exit "$vm_dir"
	fi

	rm -rf "$vm_dir"
fi

vm_mac_address="$(printf '%s' "$vm_name" | crc32 /dev/stdin | sed -E 's/.*(.{2})(.{2})(.{2})$/52:54:00:\1:\2:\3/')"

mkdir -p "$vm_dir"

vm_disk_path="$vm_dir/disk"
vm_cloud_init_dir="$vm_dir/cloud-init"
vm_cloud_init_drive_path="$vm_cloud_init_dir/cloud_init_drive.img"

mkdir -p "$images_dir" "$iso_dir"

if [ -n "$boot_drive_path_option" ]; then
	boot_drive_path=$boot_drive_path_option
	[ -f "$boot_drive_path" ] || fatal "Boot drive image '$boot_drive_path' doesn't exist"
else
	boot_drive_path="$images_dir/${boot_drive_url##*/}"
fi

if [ -n "$iso_path_option" ]; then
	iso_path=$iso_path_option
elif [ -n "$iso_url" ]; then
	iso_path=$iso_dir/${iso_url##*/}
fi

if [ "$create_boot_drive" -eq 0 ] && [ -z "$boot_drive_path_option" ] && [ ! -f "$boot_drive_path" ]; then
	echo "Downloading boot drive image from '$boot_drive_url'" >&2
	fetch "$boot_drive_url" "$boot_drive_path"
fi

if [ -n "$iso_url" ] && [ ! -f "$iso_path" ]; then
	echo "Downloading ISO from '$iso_url'" >&2
	fetch "$iso_url" "$iso_path"
fi

# xz-compressed images are decompressed into the cache once and reused
if [ "$create_boot_drive" -eq 0 ]; then
	case "$boot_drive_path" in
		*.xz)
			decompressed=${boot_drive_path%.xz}
			decompressed="$images_dir/${decompressed##*/}"
			if [ ! -f "$decompressed" ]; then
				echo "Decompressing '$boot_drive_path'" >&2
				xz -dc "$boot_drive_path" > "$decompressed.tmp" || { rm -f "$decompressed.tmp"; fatal "Failed to decompress '$boot_drive_path'"; }
				mv "$decompressed.tmp" "$decompressed"
			fi
			boot_drive_path=$decompressed
			;;
	esac
fi

if [ "$create_boot_drive" -eq 0 ] && [ -z "$boot_drive_format" ]; then
	boot_drive_format=$(qemu-img info --output=json "$boot_drive_path" 2> /dev/null | jq -r .format)
	case "$boot_drive_format" in
		qcow2 | raw) ;;
		'') fatal "Failed to detect the format of '$boot_drive_path' (not a disk image?)" ;;
		*) fatal "Unsupported boot drive format '$boot_drive_format' of '$boot_drive_path' (convert to qcow2 or raw first)" ;;
	esac
fi

if [ "$create_boot_drive" -eq 0 ]; then
	if [ "$boot_drive_format" = 'qcow2' ]; then
		qemu-img create -b "$boot_drive_path" -B "$boot_drive_format" -f "$boot_drive_format" "$vm_disk_path" "$disk_size" > /dev/null || fatal "Failed to create a boot drive for '$vm_name' from '$boot_drive_url'"
	elif [ "$boot_drive_format" = 'raw' ]; then
		vm_disk_path=$vm_disk_path.raw
		cp -a "$boot_drive_path" "$vm_disk_path" > /dev/null || fatal "Failed to copy the boot drive image for '$vm_name' from '$boot_drive_path'"
		qemu-img resize "$vm_disk_path" "$disk_size" || fatal "Failed to resize the boot drive '$vm_disk_path' to '$disk_size'"
	else
		fatal "Unknown boot drive file format '$boot_drive_format'"
	fi
else
	qemu-img create -f qcow2 "$vm_disk_path" "$disk_size" > /dev/null || fatal "Failed to create a new empty boot drive for '$vm_name'"
	boot_drive_format=qcow2
fi

[ -n "$network_tap_device_name" ] && network_type='tap' || network_type='user'

ssh_port=
if [ "$network_type" = 'user' ]; then
	ssh_port=24000
	while [ "$(ss --no-header --tcp state all sport "$ssh_port" | wc -l)" -ne 0 ]; do
		ssh_port=$((ssh_port + 1))
	done
fi

if [ "$attach_cloud_init_drive" -eq 1 ]; then
	mkdir -p "$vm_cloud_init_dir"

	ssh_key_path="$vm_dir/id_ed25519"

	ssh-keygen -t ed25519 -f "$ssh_key_path" -N '' > /dev/null || fatal "Failed to generate an ssh key for '$vm_name'"

	pub_ssh_key_path="${ssh_key_path}.pub"
	pub_ssh_key="$(cat "$pub_ssh_key_path")"

	user_data_path="$vm_cloud_init_dir/user-data"

	if [ -n "$cloud_init_user_data_path" ]; then
		cp -a "$cloud_init_user_data_path" "$user_data_path" || fatal "Failed to copy user-data from '$cloud_init_user_data_path'"
	else
		cat <<-EOF > "$user_data_path"
		#cloud-config
		disable_root: false
		users:
		  - name: root
		    lock_passwd: false
		    plain_text_passwd: "123"
		    ssh_authorized_keys:
		      - ${pub_ssh_key}
		hostname: ${vm_name}
		EOF
	fi

	if [ "$network_type" = 'user' ]; then
		cloud-localds --hostname "$vm_name" "$vm_cloud_init_drive_path" "$user_data_path" || fatal "Failed to create the cloud-init drive for '$vm_name'"
	else
		network_config_path="$vm_cloud_init_dir/network-config"

		if [ "$network_vm_dhcp" -eq 1 ]; then
			if [ "$cloud_init_network_config_version" = '1' ]; then
				fatal 'not implemented'
			elif [ "$cloud_init_network_config_version" = '2' ]; then
				cat <<-EOF > "$network_config_path"
				version: 2
				ethernets:
				  interface0:
				    match:
				      name: "e*"
				    dhcp4: true
				EOF
			else
				fatal "unknown cloud-init network-config version: '$cloud_init_network_config_version'"
			fi
		else
			[ -n "${network_vm_ip_address_cidr}" ] || fatal '--net-address-cidr is not set'
			[ -n "${network_vm_default_gateway}" ] || fatal '--net-gateway is not set'

			if [ "$cloud_init_network_config_version" = '1' ]; then
				cat <<-EOF > "$network_config_path"
				version: 1
				config:
				  - type: physical
				    name: eth0
				    mac_address: "$vm_mac_address"
				    subnets:
				      - type: static
				        address: $network_vm_ip_address_cidr
				        gateway: $network_vm_default_gateway
				        dns_nameservers:
				          - 8.8.8.8
				EOF
			elif [ "$cloud_init_network_config_version" = '2' ]; then
				cat <<-EOF > "$network_config_path"
				version: 2
				ethernets:
				  interface0:
				    match:
				      name: "e*"
				    addresses:
				      - ${network_vm_ip_address_cidr:?}
				    routes:
				      - to: 0.0.0.0/0
				        via: ${network_vm_default_gateway:?}
				    nameservers:
				      addresses:
				        - 8.8.8.8
				EOF
			else
				fatal "unknown cloud-init network-config version: '$cloud_init_network_config_version'"
			fi
		fi

		cloud-localds --hostname "$vm_name" --network-config "$network_config_path" "$vm_cloud_init_drive_path" "$user_data_path" || fatal "Failed to create the cloud-init drive for '$vm_name'"
	fi
fi

vm_uuid="$(uuidgen)"

{
	config_write vm_uuid "$vm_uuid"
	config_write vm_disk_path "$vm_disk_path"
	config_write boot_drive_format "$boot_drive_format"
	config_write memory "$memory"
	config_write cores "$cores"
	config_write kvm "$enable_kvm"
	config_write cpu "$cpu"
	config_write vnc "$vnc"
	config_write network_type "$network_type"
	config_write network_tap_device_name "$network_tap_device_name"
	config_write ssh_port "$ssh_port"
	config_write vm_mac_address "$vm_mac_address"
	config_write attach_cloud_init_drive "$attach_cloud_init_drive"
	config_write second_drive "$second_drive"
	config_write enable_spice "$enable_spice"
	config_write log_serial "$log_serial"
	config_write uefi "$uefi"
	config_write enable_tpm "$enable_tpm"
	config_write enable_qemu_guest_agent "$enable_qemu_guest_agent"
	config_write kernel_path "$kernel_path"
	config_write initramfs_path "$initramfs_path"
	config_write append_cmdline "$append_cmdline"
	config_write enable_gdb "$enable_gdb"
} > "$vm_config_path"

# the OVMF varstore is per-VM state and must be created here; everything
# else launch-related is handled by svmm-start from vmm.conf
if [ "$uefi" -eq 1 ]; then
	if [ "$uefi_empty_varstore" -eq 1 ]; then
		cp -a "$ovmf_dir/OVMF_VARS_4M.qcow2" "$vm_dir/OVMF_VARS_4M.qcow2" || fatal 'Failed to copy the OVMF varstore (is OVMF installed?)'
	else
		cp -a "$ovmf_dir/OVMF_VARS_4M.secboot.qcow2" "$vm_dir/OVMF_VARS_4M.qcow2" || fatal 'Failed to copy the OVMF varstore (is OVMF installed?)'
	fi
fi

set --
[ -z "$iso_path" ] || set -- "$@" --iso-path "$iso_path"
[ "$display_gtk" -eq 0 ] || set -- "$@" --gtk
[ "$dry_run" -eq 0 ] || set -- "$@" --dry-run
[ "$verbose" -eq 0 ] || set -- "$@" --verbose

exec svmm-start "$@" "$vm_name"
