#!/usr/bin/env sh

# shellcheck disable=SC2034 # PROG is used by svmm-common
PROG="${0##*/}"

. svmm-common

show_help()
{
	cat <<-EOF
	svmm-list [options]

	Options:
	  --no-status			don't show vm running status
	  --color <mode>		color output mode (auto, always, never), default: auto
	  -v, --verbose			print executed commands
	  -h, --help			show help and exit
	EOF
}

verbose=0
show_status=1
color_option=auto
while true; do
	case "$1" in
	--no-status)
		show_status=0
		shift
		;;
	--color)
		[ "$#" -ge 2 ] || fatal 'Not enough arguments: --color'
		color_option=$2
		shift 2
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	-h | --help)
		show_help
		exit 0
		;;
	-*)
		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
		show_help
		exit 1
		;;
	*)
		break
		;;
	esac
done

[ "$verbose" -eq 0 ] || set -x

for vm_dir in "$vmm_dir"/*; do
	[ -d "$vm_dir" ] || continue

	vm_name="${vm_dir##*/}"

	if [ "$show_status" -eq 1 ]; then
		printf '%-30s ' "$vm_name"
		enable_color=0
		case "$color_option" in
			'always') enable_color=1 ;;
			'auto') [ -t 1 ] && enable_color=1 ;;
			'never') ;;
			*) fatal "unknown color mode '$color_option'" ;;
		esac
		status=
		color=
		if svmm-is-qemu-running "$vm_name"; then
			status='Running'
			color='\e[0;32m'
		else
			status='Stopped'
			color='\e[0;31m'
		fi

		if [ "$enable_color" -eq 1 ]; then
			printf '%b%s\e[0m\n' "$color" "$status"
		else
			printf '%s\n' "$status"
		fi
	else
		printf '%s\n' "$vm_name"
	fi
done
